title: Tailo Mateus Gonsalves
email: tailogonsalves@gmail.com

disqus-shortname: tailo_mateus
url: "https://tailomateus.github.io" 

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 20
paginate_path: /page:num/

keep_files: ['.htaccess']
include: ['.htaccess']

#social
twitter: https://twitter.com/@tailomgonsalves
github: https://github.com/TailoMateus

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
