title: Tailo Mateus Gonsalves
email: tailogonsalves@gmail.com

disqus-shortname: tailo_mateus
url: "http://tailomateus.github.io" 

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 20
paginate_path: /page:num/

#social
twitter: http://twitter.com/@tailomgonsalves
github: http://github.com/TailoMateus

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
