# Build settings
# markdown: redcarpet
markdown: MyCustomProcessor
highlighter: pygments

# Site settings
title: "Tailo - Desenvolvimento Web"
subtitle: "Desenvolvimento Web"
#description: > # this means to ignore newlines until "email:"
#   A Jekyll theme - Medium inspired

email: tailogonsalves@gmail.com
#blog logo
logo: "/assets/images/botaoMenu.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Tailo Mateus Gonsalves'
author: 'Tailo Mateus Gonsalves'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://tailomateus.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/tailo.mateus
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/TailoMateus
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
