title: Tailo Mateus Gonsalves
email: tailogonsalves@gmail.com

url: "http://tailomateus.github.io" 

#social
twitter: http://twitter.com/@tailomgonsalves
github: http://github.com/TailoMateus

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
